:idprefix: id_
:source-highlighter: pygments

== Spring Boot Forge addon

image:https://forge.ci.cloudbees.com/buildStatus/icon?job=springboot-addon["Build Status", link="https://forge.ci.cloudbees.com/job/springboot-addon"]
image:http://img.shields.io/:license-EPL-blue.svg["License", link="https://www.eclipse.org/legal/epl-v10.html"]
image:https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot"]

This addon provides *standalone* functionality, and *exports services* for use in other addons.

=== Prerequisites

- JBoss Forge >= 3.7
- Java 8

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/springboot-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|maven
|no
|no

|parser-java
|no
|no

|parser-json
|no
|no

|parser-yaml
|no
|no

|cdi
|no
|no

|scaffold
|no
|no

|cdi
|no
|no

|rest-client
|no
|no

|templates
|no
|no
|===

== Features
The Spring Boot addon reuses standard commands adding options and/or new commands only when required.

Supported commands::

- `project-new` will create Spring Boot projects if you specify the `spring-boot` type options:
+
----
project-new --named example --type spring-boot --spring-boot-version 1.5.3 --dependencies actuator web
----
You can specify which Spring Boot version to use using the `--spring-boot-version`, defaulting to `1.5.4.RELEASE`.
You can add Spring Boot dependencies using the `--dependencies` option, specifying a space-separated list of
dependencies. Note that pressing tab after typing `--dependencies` option will result in Forge retrieving the list of
 available dependencies that can then be auto-completed.

- `jpa-setup` will set things up to use JPA with an Hibernate persistence provider and configured with the
appropriate driver and sane default settings. Also, by default, if no database is specified, H2 is used.

- `jpa-new-entity` will create a new JPA entity using a Spring Boot flavor as, for each entity, we also generate an
associated `CrudRepository` and a `RepositoryConfiguration` class.

- `rest-generate-endpoints-from-entities` will generate JAX-RS RESTful endpoints based on JPA entities. The behavior
is customized for Spring Boot and defaults to use the Apache CXF stack. The Spring Boot mode is activated by using
a custom `SPRING_BOOT_JPA_ENTITY` generator:
+
----
rest-generate-endpoints-from-entities --generator SPRING_BOOT_JPA_ENTITY --targets ...
----
Note that the resources derived from the JPA entities are currently limited to JSON representations (with the Jackson
 JSON stack).

- `rest-new-endpoint`: to document, not well tested

- `rest-new-cross-origin-resource-sharing-filter` will create a CORS filter so that cross-origin requests are allowed
. The filter is also annotated so that it is automatically recognized by the Apache CXF implementation.



TODO: Check this part
Use your Config File::
If you want to use a YAML config file containing the dependencies to be used for your project, you can create such a file according to the convention defined by
http://docs.spring.io/initializr/docs/current/reference/htmlsingle/#configuration-format[Spring Initialzr] and pass the reference to this file using the following ENV variable `SPRING_BOOT_CONFIG_FILE`
+
[source,java]
----
export SPRING_BOOT_CONFIG_FILE=file:///path/to/your/spring-boot-application.yaml

spring-boot-new-project --spring-boot-version 1.4.3 --dependencies ...
----
+
An example of such a file is link:src/main/resources/spring-boot-application.yaml[available]. Only the dependencies section will be used to
populate the pom.xml.