:idprefix: id_
:source-highlighter: pygments

== Spring Boot Forge addon

image:https://forge.ci.cloudbees.com/buildStatus/icon?job=spring-boot-addon["Build Status", link="https://forge.ci.cloudbees.com/job/spring-boot-swarm-addon"]
image:http://img.shields.io/:license-EPL-blue.svg["License", link="https://www.eclipse.org/legal/epl-v10.html"]
image:https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot"]

This addon provides *standalone* functionality, and *exports services* for use in other addons.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/ebcnOopZFWs" frameborder="0" allowfullscreen></iframe>
++++

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/springboot-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|maven
|no
|no

|parser-java
|no
|no

|cdi
|no
|no
|===

== Features
New Project command::
If you're working in an existing maven project, just type `spring-boot-new-project` if you're in shell.
It should read Spring Boot: New Project if you're in a GUI environment:
+
[source,java]
----
spring-boot-new-project
----
+
And that's it!

Select the Version::
To specify the Spring Boot version to be used, pass as parameter this attribute `--spring-boot-version `
+
[source,java]
----
spring-boot-new-project --spring-boot-version 1.4.1.RELEASE
----

If you don't specify the version, than a list will be displayed where one of the item is the default value.


Add Dependency::
You can install Spring Boot dependencies by using the command `spring-boot-new-project` followed by the parameter `--dependencies`:
+
[source,java]
----
[demo]$ spring-boot-new-project --dependencies

TODO
----
+
You can choose any dependency you want to install.
