:idprefix: id_
:source-highlighter: pygments

== Spring Boot Forge addon

image:https://forge.ci.cloudbees.com/buildStatus/icon?job=springboot-addon["Build Status", link="https://forge.ci.cloudbees.com/job/springboot-addon"]
image:http://img.shields.io/:license-EPL-blue.svg["License", link="https://www.eclipse.org/legal/epl-v10.html"]
image:https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot"]

This addon provides *standalone* functionality, and *exports services* for use in other addons.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/ebcnOopZFWs" frameborder="0" allowfullscreen></iframe>
++++

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/springboot-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|maven
|no
|no

|parser-java
|no
|no

|cdi
|no
|no
|===

== Features
New Project command::
If you're working in an existing maven project, just type `spring-boot-new-project` if you're in shell.
It should read Spring Boot: New Project if you're in a GUI environment:
+
[source,java]
----
spring-boot-new-project
----
+
And that's it!

Select the Version::
To specify the Spring Boot version to be used, pass as parameter this attribute `--spring-boot-version `
+
[source,java]
----
spring-boot-new-project --spring-boot-version 1.4.1.RELEASE
----

If you don't specify the version, than a list will be displayed where one of the item is the default value.


Add Dependency::
You can install Spring Boot dependencies by using the command `spring-boot-new-project` followed by the parameter `--dependencies`:
+
[source,java]
----
spring-boot-new-project --dependencies
Display all 113 possibilities? (y or n)
activiti                       cassandra                      cluster-redis                  feign                          jms-hornetq                    neo4j                          sleuth-stream                  websocket
actuator                       circuit-breaker-pcf            cluster-zookeeper              flyway                         jooq                           postgresql                     solr                           zipkin-client
actuator-docs                  cloud-bootstrap                config-client                  freemarker                     jpa                            ratpack                        spring-cloud-kubernetes        zipkin-server
amqp                           cloud-bus-amqp                 config-client-pcf              gemfire                        ldap                           reactive-web                   sql-server                     zipkin-stream
aop                            cloud-bus-kafka                config-server                  groovy-templates               linkedin                       redis                          stream-kafka                   zipkin-ui
apache-camel                   cloud-connectors               configuration-processor        h2                             liquibase                      remote-shell                   stream-rabbit                  zookeeper-configuration
apache-camel-zipkin            cloud-contract-stub-runner     consul-configuration           hateoas                        local-data-flow-server         rest-docs                      thymeleaf                      zookeeper-discovery
apache-derby                   cloud-contract-verifier        consul-discovery               hsqldb                         lombok                         rest-repositories              turbine                        zuul
atomikos-jta                   cloud-contract-wiremock        couchbase                      hystrix                        mail                           rest-repositories-hal-browser  turbine-stream
aws-core                       cloud-foundry-discovery        data-flow-shell                hystrix-dashboard              mobile                         retry                          twitter
aws-jdbc                       cloud-oauth2                   devtools                       integration                    mongodb                        ribbon                         vaadin
aws-messaging                  cloud-security                 elasticsearch                  jdbc                           mustache                       security                       validation
batch                          cloud-task                     eureka-discovery               jersey-jax-rs                  mybatis                        service-registry-pcf           velocity
bitronix-jta                   cluster-etcd                   eureka-server                  jms-activemq                   mysql                          session                        web
cache                          cluster-hazelcast              facebook                       jms-artemis                    narayana-jta                   sleuth                         web-services
----
+
You can choose any dependency you want to install.
