:idprefix: id_
:source-highlighter: pygments

== Spring Boot Forge addon

image:https://forge.ci.cloudbees.com/buildStatus/icon?job=springboot-addon["Build Status", link="https://forge.ci.cloudbees.com/job/springboot-addon"]
image:http://img.shields.io/:license-EPL-blue.svg["License", link="https://www.eclipse.org/legal/epl-v10.html"]
image:https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/org.jboss.forge.addon/spring-boot"]

This addon provides *standalone* functionality, and *exports services* for use in other addons.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/ebcnOopZFWs" frameborder="0" allowfullscreen></iframe>
++++

=== Installation

From Forge CLI:

[source,shell]
----
addon-install-from-git --url https://github.com/forge/springboot-addon.git
----

=== Depends on
[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|maven
|no
|no

|parser-java
|no
|no

|parser-yaml
|no
|no

|cdi
|no
|no
|===

== Features
Setup a Spring Boot Project::
First, create a Spring Boot project where the groupId or top level package is by example `org.demo`, the artifact which is also the name of the folder `example` and the version `1.0.0-SNAPSHOT`
using the Forge shell
+
----
forge
...
To quit the shell, type 'exit'.

[Temp]$ project-new --named example \
                    --version 1.0.0-SNAPSHOT \
                    --top-level-package org.demo \
                    --type spring-boot
----
+
And that's it!

Specify Version::
To specify the Spring Boot version to be used, pass as parameter this attribute `--spring-boot-version `
+
[source,java]
----
project-new --named example \
            --version 1.0.0-SNAPSHOT  \
            --top-level-package org.demo  \
            --type spring-boot  \
            --spring-boot-version 1.4.1
----

If you don't specify the version, than a list will be displayed where one of the item is the default value.

Add Dependency::
You can install Spring Boot dependencies by using the command `spring-boot-setup-project` followed by the parameter `--dependencies`:
+
[source,java]
----
spring-boot-setup-project --dependencies
Display all 113 possibilities? (y or n)
activiti                       cassandra                      cluster-redis                  feign                          jms-hornetq                    neo4j                          sleuth-stream                  websocket
actuator                       circuit-breaker-pcf            cluster-zookeeper              flyway                         jooq                           postgresql                     solr                           zipkin-client
actuator-docs                  cloud-bootstrap                config-client                  freemarker                     jpa                            ratpack                        spring-cloud-kubernetes        zipkin-server
amqp                           cloud-bus-amqp                 config-client-pcf              gemfire                        ldap                           reactive-web                   sql-server                     zipkin-stream
aop                            cloud-bus-kafka                config-server                  groovy-templates               linkedin                       redis                          stream-kafka                   zipkin-ui
apache-camel                   cloud-connectors               configuration-processor        h2                             liquibase                      remote-shell                   stream-rabbit                  zookeeper-configuration
apache-camel-zipkin            cloud-contract-stub-runner     consul-configuration           hateoas                        local-data-flow-server         rest-docs                      thymeleaf                      zookeeper-discovery
apache-derby                   cloud-contract-verifier        consul-discovery               hsqldb                         lombok                         rest-repositories              turbine                        zuul
atomikos-jta                   cloud-contract-wiremock        couchbase                      hystrix                        mail                           rest-repositories-hal-browser  turbine-stream
aws-core                       cloud-foundry-discovery        data-flow-shell                hystrix-dashboard              mobile                         retry                          twitter
aws-jdbc                       cloud-oauth2                   devtools                       integration                    mongodb                        ribbon                         vaadin
aws-messaging                  cloud-security                 elasticsearch                  jdbc                           mustache                       security                       validation
batch                          cloud-task                     eureka-discovery               jersey-jax-rs                  mybatis                        service-registry-pcf           velocity
bitronix-jta                   cluster-etcd                   eureka-server                  jms-activemq                   mysql                          session                        web
cache                          cluster-hazelcast              facebook                       jms-artemis                    narayana-jta                   sleuth                         web-services
----
+
You can choose any dependency you want to install.

If you know which dependencies you need, you can pass them as a list of items separated by a space. Here is an example where you will pass the dependency
about `web` and `actuator`
----
spring-boot-setup-project --spring-boot-version 1.4.3 --dependencies actuator web
----

Use your Config File::
If you want to use a YAML config file containing the dependencies to be used for your project, you can create such a file according to the convention defined by
http://docs.spring.io/initializr/docs/current/reference/htmlsingle/#configuration-format[Spring Initialzr] and pass the reference to this file using the following ENV variable `SPRING_BOOT_CONFIG_FILE`
+
[source,java]
----
export SPRING_BOOT_CONFIG_FILE=file:///path/to/your/spring-boot-application.yaml

spring-boot-new-project --spring-boot-version 1.4.3 --dependencies ...
----
+
An example of such a file is link:src/main/resources/spring-boot-application.yaml[available]. Only the dependencies section will be used to
populate the pom.xml.